export interface AdvisoryInput {
  packageName: string;
  affectedVersions: string;
  patchedVersions?: string;
  summary: string;
  description: string;
  severity: "critical" | "high" | "medium" | "low";
  cwe?: string[];
  iocs?: string[];
  references?: string[];
}

export interface AdvisoryOutput {
  markdown: string;
  json: object;
}

export function generateAdvisory(input: AdvisoryInput): AdvisoryOutput {
  const ghsaId = `GHSA-bnpm-${input.packageName.replace(/[^a-z0-9]/gi, "").slice(0, 8)}`;
  const cweList = input.cwe ?? ["CWE-506"];

  const markdown = [
    `# ${ghsaId}: Malicious code in ${input.packageName}`,
    "",
    "## Summary",
    input.summary,
    "",
    "## Description",
    input.description,
    "",
    "## Affected versions",
    input.affectedVersions,
    "",
    input.patchedVersions ? `## Patched versions\n${input.patchedVersions}\n` : "",
    "## Severity",
    `**${input.severity}**`,
    "",
    input.iocs?.length
      ? `## Indicators of compromise\n${input.iocs.map((i) => `- \`${i}\``).join("\n")}\n`
      : "",
    "## CWE",
    cweList.map((c) => `- ${c}`).join("\n"),
    "",
    "## References",
    ...(input.references ?? ["https://betternpm.dev/advisories"]).map((r) => `- ${r}`),
    "",
    "---",
    "*Draft generated by bnpm advisory generator (NPM-013)*",
  ]
    .filter(Boolean)
    .join("\n");

  const json = {
    id: ghsaId,
    schema_version: "1.4.0",
    summary: input.summary,
    details: input.description,
    severity: [
      { type: "CVSS_V3", score: input.severity === "critical" ? "10.0" : "8.0" },
    ],
    affected: [
      {
        package: { ecosystem: "npm", name: input.packageName },
        ranges: [{ type: "SEMVER", events: [{ introduced: "0" }] }],
        versions: input.affectedVersions.split(",").map((v) => v.trim()),
      },
    ],
    references: (input.references ?? []).map((url) => ({ type: "WEB", url })),
    credits: [{ name: "bnpm emergency advisory generator", type: "FINDER" }],
    database_specific: { iocs: input.iocs ?? [], cwe_ids: cweList },
  };

  return { markdown, json };
}
