import type { BlocklistBundle } from "./schema.js";

/** Embedded threat intel from 2025–2026 npm supply-chain incidents (NPM-006, NPM-007, NPM-008). */
export const EMBEDDED_BLOCKLIST: BlocklistBundle = {
  version: "1.0.0",
  updated_at: "2026-06-01T00:00:00.000Z",
  entries: [
    {
      package: "axios",
      version: "1.14.1",
      reason: "Compromised maintainer account; injected plain-crypto-js RAT dropper (GHSA-fw8c-xr5c-95f9)",
      severity: "critical",
      action: "block",
      source: "ghsa",
      iocs: [
        "plain-crypto-js@4.2.1",
        "node_modules/plain-crypto-js/setup.js",
        "sfrclak.com:8000",
        "/Library/Caches/com.apple.act.mond",
        "%PROGRAMDATA%\\wt.exe",
        "/tmp/ld.py",
      ],
      remediation: "Pin axios@1.14.0 or earlier; rotate all secrets if installed",
    },
    {
      package: "axios",
      version: "0.30.4",
      reason: "Legacy branch compromise; same UNC1069/Sapphire Sleet campaign as 1.14.1",
      severity: "critical",
      action: "block",
      source: "ghsa",
      iocs: ["plain-crypto-js@4.2.1", "node_modules/plain-crypto-js/setup.js"],
      remediation: "Pin axios@0.30.3 or earlier; rotate all secrets if installed",
    },
    {
      package: "plain-crypto-js",
      version_range: "4.2.1",
      reason: "Phantom dependency staged for axios compromise; XOR-obfuscated postinstall RAT",
      severity: "critical",
      action: "block",
      source: "curated",
      iocs: ["OrDeR_7077", "setup.js"],
    },
    {
      package: "@tanstack/react-query",
      version_range: ">=5.77.0 <=5.77.2",
      reason: "May 2026 CI/CD chain attack; router_init.js credential exfiltration",
      severity: "critical",
      action: "block",
      source: "incident-2026-05",
      iocs: ["@tanstack/setup", "router_init.js", "github:tanstack/router#79ac49eed"],
      remediation: "Rotate CI/CD and cloud credentials; audit lockfile for May 11 2026 publishes",
    },
    {
      package: "@tanstack/react-router",
      version_range: ">=1.120.0 <=1.120.3",
      reason: "Malicious publish via poisoned GitHub Actions cache + OIDC token theft",
      severity: "critical",
      action: "block",
      source: "incident-2026-05",
      iocs: ["router_init.js", "@tanstack/setup"],
    },
    {
      package: "@tanstack/router-core",
      version_range: ">=1.120.0 <=1.120.3",
      reason: "Part of coordinated @tanstack/* compromise (42 packages, 84 versions)",
      severity: "critical",
      action: "block",
      source: "incident-2026-05",
      iocs: ["router_init.js"],
    },
    {
      package: "@tanstack/query-core",
      version_range: ">=5.77.0 <=5.77.2",
      reason: "Transitive target in TanStack May 2026 incident",
      severity: "critical",
      action: "block",
      source: "incident-2026-05",
    },
    {
      package: "eslint-config-prettierr",
      version_range: "*",
      reason: "Typosquat of eslint-config-prettier; known malware dropper pattern",
      severity: "high",
      action: "block",
      source: "typosquat-heuristic",
      remediation: "Did you mean eslint-config-prettier?",
    },
    {
      package: "crossenv",
      version_range: "*",
      reason: "Typosquat of cross-env; install script exfiltration",
      severity: "high",
      action: "block",
      source: "typosquat-heuristic",
      remediation: "Did you mean cross-env?",
    },
    {
      package: "event-stream",
      version: "3.3.6",
      reason: "Historical flatmap-stream compromise; retained for regression tests",
      severity: "high",
      action: "warn",
      source: "curated",
      expires_at: null,
    },
  ],
};
