import type { FixBranchSpec, FixSuggestion, ScanResult } from "../types.js";
import { orchestrateFixes } from "../ai/fix-orchestrator.js";

/**
 * Auto-fix branch creator spec (MOB-021).
 * Generates a branch + PR payload from scan fix suggestions.
 */
export function createFixBranchSpec(
  result: ScanResult,
  options: { baseBranch?: string; maxFixes?: number } = {},
): FixBranchSpec {
  const baseBranch = options.baseBranch ?? "main";
  const fixes = orchestrateFixes(result).filter((f) => f.automated);
  const selected = fixes.slice(0, options.maxFixes ?? 5);

  const branchName = `shipkit/fix-${result.graph.root}-${Date.now()}`;
  const title = `fix(shipkit): resolve ${selected.length} release blockers`;
  const body = buildPrBody(result, selected);

  return {
    branchName,
    baseBranch,
    title,
    body,
    files: selected.map((fix) => ({
      path: inferFilePath(fix),
      content: `# ShipKit auto-fix for ${fix.issueId}\n# ${fix.description}\n`,
    })),
    pullRequestUrl: `https://github.com/org/${result.graph.root}/compare/${baseBranch}...${branchName}?expand=1`,
  };
}

function buildPrBody(result: ScanResult, fixes: FixSuggestion[]): string {
  const lines = [
    "## ShipKit Auto-Fix",
    "",
    `Health score: **${result.healthScore}/100**`,
    `Expo SDK: ${result.expo.sdkVersion ?? "unknown"}`,
    "",
    "### Fixes applied",
    "",
  ];

  for (const fix of fixes) {
    lines.push(`- [${(fix.confidence * 100).toFixed(0)}%] ${fix.description}`);
  }

  lines.push("", "---", "*Generated by ShipKit*");
  return lines.join("\n");
}

function inferFilePath(fix: FixSuggestion): string {
  if (fix.issueId.startsWith("16kb-")) {
    const pkg = fix.issueId.replace("16kb-", "");
    return `package.json#${pkg}`;
  }
  if (fix.issueId.startsWith("preflight-")) {
    return `app.config.js#${fix.issueId}`;
  }
  return `fixes/${fix.issueId}.md`;
}

export function formatGitHubPrComment(result: ScanResult): string {
  const errors = result.preflight.filter((v) => !v.passed && v.severity === "error");
  const lines = [
    `## ShipKit Scan Results`,
    "",
    `**Health score:** ${result.healthScore}/100`,
    `**Expo SDK:** ${result.expo.sdkVersion ?? "unknown"}`,
    `**16KB issues:** ${result.compliance.issues.length}`,
    `**Preflight errors:** ${errors.length}`,
    "",
  ];

  if (errors.length > 0) {
    lines.push("### Critical preflight failures");
    for (const e of errors.slice(0, 5)) {
      lines.push(`- [${e.store}] ${e.title}: ${e.message}`);
    }
    if (errors.length > 5) {
      lines.push(`- ... and ${errors.length - 5} more`);
    }
  }

  lines.push("", `<sub>Powered by ShipKit</sub>`);
  return lines.join("\n");
}
