/* ============================================
   UNIFIED PORTFOLIO DATA
   One narrative.
   ============================================ */

const RESUME_DATA = {
  identity: {
    name: 'William Lopez-Cordero',
    email: 'williamlopezc@gmail.com',
    phone: '(213) 210-9603',
    location: 'Los Angeles, CA',
    linkedin: 'william-lopez-cordero',
    github: 'wcordelo',
    education: 'BS Aerospace Engineering, MIT (2014–2019)',
  },

  disciplines: [
    { key: 'ai', label: 'AI Automation', count: 'Pipelines · Agents · LLMs' },
    { key: 'software', label: 'Full Stack', count: 'React · Next · TypeScript' },
    { key: 'protocol', label: 'Protocol', count: 'Solidity · EVM · viem' },
    { key: 'infra', label: 'Data Infra', count: 'ClickHouse · Kafka · Go' },
    { key: 'aerospace', label: 'Aerospace', count: 'CFD · Flight Systems' },
  ],

  metrics: [
    { v: '60K+', l: 'Users served on production platform' },
    { v: '$2M+', l: 'Protocol revenue driven at Bello' },
    { v: '$1M+', l: 'Onchain incentives distributed' },
    { v: '1M+', l: 'Downloads powered by AI pipelines' },
    { v: '30%', l: 'Reduction in mortgage origination time' },
    { v: '10×', l: 'Query latency reduction on analytics' },
  ],

  hero: {
    titles: ['ai engineer', 'protocol engineer', 'infra engineer'],
    tag: 'Solving the hardest problems.',
    subtitle: "MIT aerospace engineer turned founding engineer. I build systems — from spacecraft sequencing at JPL to onchain protocols distributing $1M+ in incentives. 10+ years across aerospace, consumer, fintech, and web3.",
  },

  experience: [
    {
      id: 'bello',
      role: 'Founding Engineer',
      org: 'Bello',
      period: '2023 — Present',
      location: 'Remote',
      status: 'current',
      discipline: ['software', 'protocol', 'infra'],
      blurb: 'Founding engineer at a web3 creator platform. Scaled to 60K+ users, drove $2M+ in protocol revenue, and distributed $1M+ in onchain incentives.',
      highlights: [
        'Architected full-stack platform (React, Next.js, TypeScript) serving 60K+ users',
        'Led AWS/GCP infra using Pulumi — reduced manual ops by 90%+, enabled auto-scaling',
        'Shipped AI content pipelines (aggregation, validation, generation) powering 1M+ downloads',
        'Launched Blueprint Protocol + creator monetization — drove $2M+ protocol revenue',
        'Designed onchain loyalty/rewards system distributing $1M+; retention 30% → 60%',
        'Built ClickHouse + BigQuery analytics — 10× query latency reduction',
        'Ingestion across Ethereum, Base, Optimism, Zora via event-driven pipelines',
        'Wallet integrations via viem, wagmi, ethers, Dynamic',
      ],
      stack: ['Next.js', 'TypeScript', 'Solidity', 'viem', 'ClickHouse', 'Pulumi', 'AWS'],
    },
    {
      id: 'dragverse',
      role: 'Co-Founder',
      org: 'Dragverse',
      period: '2023 — 2025',
      location: 'Remote',
      discipline: ['protocol', 'software'],
      blurb: 'Co-founded a decentralized social platform built on Lens Protocol with user-owned identity and content.',
      highlights: [
        'Built decentralized applications on Lens Protocol',
        'Designed user-owned identity and content systems',
      ],
      stack: ['Lens Protocol', 'React', 'Solidity'],
    },
    {
      id: 'elphi',
      role: 'Co-Founder & Head of Architecture',
      org: 'Elphi',
      period: '2018 — 2023',
      location: 'Remote',
      discipline: ['software', 'infra'],
      blurb: 'Co-founded a mortgage platform. Took systems 0→1 into paying customers and led the architecture org through seed-stage fundraising.',
      highlights: [
        'Architected mortgage platform — reduced loan origination time by 30%+',
        'Built cloud-native infra on GCP + Firebase supporting production workloads',
        'Managed and mentored 10+ engineers across frontend, backend, and infra',
        'Delivered multiple 0→1 systems that converted into paying customers',
        'Improved system efficiency by 25% through performance optimization',
        'Established CI/CD, testing, monitoring — improving deployment speed and stability',
      ],
      stack: ['GCP', 'Firebase', 'Node.js', 'React', 'Postgres'],
    },
    {
      id: 'lockheed',
      role: 'Aerospace Engineer',
      org: 'Lockheed Martin · Skunk Works',
      period: '2018',
      location: 'Palmdale, CA',
      discipline: ['aerospace'],
      blurb: 'Thermodynamic and structural analysis inside Skunk Works — the legendary black-project shop at Lockheed.',
      highlights: [
        'Thermodynamic analysis of aircraft engine performance under varying conditions',
        'Modeled wing structures using CATIA for outer wing design',
        'Conducted stress analysis ensuring structural integrity',
        'Analyzed system-level data transfer across aircraft architecture',
      ],
      stack: ['CATIA', 'MATLAB', 'Thermo'],
    },
    {
      id: 'mit-ssl',
      role: 'Space Systems Engineer',
      org: 'MIT Space Systems Lab · OSIRIS-REx',
      period: '2016 — 2017',
      location: 'Cambridge, MA',
      discipline: ['aerospace'],
      blurb: 'Validated the REXIS instrument cover for a 2-year deep-space mission. Hardware that is now orbiting Bennu.',
      highlights: [
        'Developed test plans validating REXIS instrument cover compatibility',
        'Built thermal resistance models and hardware replicas for vacuum chamber testing',
        'Verified Frangibolt Assembly reliability for 2-year deep space mission',
      ],
      stack: ['Vacuum Chamber', 'Thermal Models', 'MATLAB'],
    },
    {
      id: 'facebook',
      role: 'Software Engineer',
      org: 'Facebook',
      period: '2016',
      location: 'Menlo Park, CA',
      discipline: ['software'],
      blurb: 'Shipped GIF comments to News Feed. Used by millions at launch.',
      highlights: [
        'Shipped GIF comments feature to News Feed used by millions',
        'Built full-stack functionality with React, PHP, Hack, JavaScript',
      ],
      stack: ['React', 'PHP', 'Hack'],
    },
    {
      id: 'jpl',
      role: 'Software Engineer',
      org: 'NASA JPL · Europa Mission',
      period: '2014',
      location: 'Pasadena, CA',
      discipline: ['aerospace', 'software'],
      blurb: 'Built sequencing software for spacecraft operations on the Europa Mission. My first job wrote code that will fly to Jupiter.',
      highlights: [
        'Developed sequencing software for spacecraft operations',
        'Built model predictors, derivators, and validation systems for mission planning',
        'Designed data visualization and simulation tools',
      ],
      stack: ['Python', 'Simulation'],
    },
    {
      id: 'google',
      role: 'Software Engineer',
      org: 'Google',
      period: '2014',
      location: 'Kirkland, WA',
      discipline: ['software'],
      blurb: 'Summer internship. Presented final product to senior engineers.',
      highlights: [
        'Built and deployed a full-stack web application using Python, App Engine',
        'Presented final product to senior engineers',
      ],
      stack: ['Python', 'App Engine'],
    },
  ],

  caseStudies: [
    {
      id: 'ai-podcast',
      title: 'AI Podcast Series',
      context: 'Bello · 2025',
      year: '2025',
      summary: 'End-to-end automated AI audio podcast — generation, editing, and distribution with zero human-in-the-loop. Hit #1 in UK and #3 in US charts with 1M+ downloads.',
      role: 'Systems architecture, AI pipeline, automation',
      metrics: [['#1', 'UK charts'], ['#3', 'US charts'], ['1M+', 'downloads']],
      tags: ['LLM', 'TTS', 'Pipeline', 'Automation'],
    },
    {
      id: 'blueprint',
      title: 'Blueprint Protocol',
      context: 'Bello',
      year: '2024',
      summary: 'Designed and shipped an onchain creator-monetization protocol that drove $2M+ in revenue and distributed $1M+ to creators and fans across Ethereum, Base, Optimism and Zora.',
      role: 'Protocol architecture, smart contracts, backend',
      metrics: [['$2M+', 'revenue'], ['$1M+', 'distributed'], ['60K+', 'users']],
      tags: ['Solidity', 'viem', 'Multi-chain', 'Incentives'],
    },
    {
      id: 'onchain-analytics',
      title: 'Multi-chain Analytics Pipeline',
      context: 'Bello',
      year: '2024',
      summary: 'Event-driven ingestion across four EVM chains feeding ClickHouse + BigQuery. 10× query-latency reduction powered retention modeling and incentive distribution at scale.',
      role: 'Infrastructure, data engineering',
      metrics: [['10×', 'faster queries'], ['4', 'chains'], ['1M+', 'events/day']],
      tags: ['ClickHouse', 'BigQuery', 'Kafka', 'Go'],
    },
    {
      id: 'elphi-platform',
      title: 'Elphi Mortgage Platform',
      context: 'Elphi · 5 years',
      year: '2018–2023',
      summary: 'Co-founded and architected a cloud-native mortgage platform that reduced loan origination time by 30%+. Grew engineering org from 2 to 10+ across FE, BE and infra.',
      role: 'Head of Architecture, co-founder',
      metrics: [['30%', 'faster origination'], ['10+', 'eng team'], ['25%', 'efficiency gain']],
      tags: ['GCP', 'Firebase', 'Node.js', 'React'],
    },
    {
      id: 'rexis',
      title: 'REXIS Cover · OSIRIS-REx',
      context: 'MIT SSL · NASA',
      year: '2016–2017',
      summary: 'Validated the Frangibolt Assembly and instrument cover for a 2-year deep-space mission to asteroid Bennu. Thermal + vacuum testing for hardware that had to survive the unsurvivable.',
      role: 'Space systems engineer',
      metrics: [['2yr', 'mission'], ['Bennu', 'asteroid'], ['1', 'chance']],
      tags: ['Thermal', 'Vacuum', 'Flight Hardware'],
    },
  ],

  projects: [
    {
      title: 'Blended Wing Body Aircraft Redesign',
      summary: 'Used XFOIL and AVL to redesign a blended-wing-body aircraft — improving static stability at cruise.',
      tags: ['XFOIL', 'AVL', 'CFD'],
      kind: 'Aerospace',
    },
    {
      title: 'Rocket Avionics System',
      summary: 'Telemetry, GPS tracking, and real-time flight data systems for a hobby-class rocket.',
      tags: ['Telemetry', 'GPS', 'Avionics'],
      kind: 'Aerospace',
    },
    {
      title: 'Dragverse',
      summary: 'Decentralized social app built on Lens Protocol with user-owned identity and content.',
      tags: ['Lens', 'React', 'Solidity'],
      kind: 'Web3',
    },
    {
      title: 'Blueprint Protocol',
      summary: 'Onchain creator-monetization protocol that generated $2M+ in protocol revenue.',
      tags: ['Solidity', 'Multi-chain'],
      kind: 'Web3',
    },
  ],

  skills: {
    'Languages': ['TypeScript', 'Go', 'Python', 'Solidity', 'SQL', 'MATLAB'],
    'Frontend': ['React', 'Next.js', 'Tailwind', 'Vite', 'viem', 'wagmi'],
    'Backend': ['Node.js', 'Express', 'Cloud Run', 'GraphQL'],
    'Data & Infra': ['ClickHouse', 'BigQuery', 'Postgres', 'Kafka', 'Pulsar', 'Pulumi'],
    'Cloud': ['AWS', 'GCP', 'Azure', 'Firebase', 'Docker'],
    'Blockchain': ['EVM', 'Forge', 'ethers', 'Dynamic'],
    'Aerospace': ['CATIA', 'XFOIL', 'AVL', 'CFD', 'Thermo', 'Flight Dynamics'],
  },

  writing: [
    { title: 'Designing onchain incentive systems that don\'t get drained', date: '2025.03', read: '12 min', tag: 'Protocol' },
    { title: 'From spacecraft sequencing to shipping at web-scale', date: '2024.11', read: '8 min', tag: 'Career' },
    { title: 'ClickHouse in production: lessons from 10× latency gains', date: '2024.08', read: '15 min', tag: 'Infra' },
    { title: 'What Skunk Works taught me about engineering culture', date: '2024.05', read: '6 min', tag: 'Notes' },
    { title: 'Building Blueprint: a multi-chain creator protocol', date: '2024.02', read: '18 min', tag: 'Protocol' },
  ],

  consulting: {
    pitch: "I work with a small number of teams each year on protocol architecture, infra scaling, and turning 0→1 products into production systems.",
    services: [
      { title: 'Protocol Architecture', blurb: 'Smart contract design, incentive mechanisms, and multi-chain deployments for creator-economy and defi protocols.' },
      { title: 'Infra & Data', blurb: 'Analytics pipelines, ClickHouse + BigQuery, event-driven ingestion at scale. 10× query improvements are normal.' },
      { title: '0→1 Engineering', blurb: 'Founding-engineer-level work. Architecture, team scaling, and shipping production systems fast without accumulating debt.' },
    ],
  },
};

window.RESUME_DATA = RESUME_DATA;
